public class greater 
{
    Public void Calc (integer Num1, integer Num2, integer Num3)
    {
        If(Num1>Num2 && Num1>Num3)
        {
            System.debug('The greater Number is: '+Num1);
        }
        Else if(Num2>Num1 && Num2>Num3)
        {
            System.debug('The greater Number is: '+Num2);
        }
        Else
        {
            System.debug('The greater Numbere is:'+Num3);
        }
    
    }
    
}