public class recttri 
{
    
    Public Void MaiCalc()
{
    
}


   Void RectangleArea(Decimal L, Decimal B)
{
    Decimal R;
    R=2*L*B;
    System.debug('The Perimeter of the Rectangle is '+R);
}

  void TraingleArea(Decimal H, Decimal B)
{
    Decimal R;
    R=0.5*H*B;
    System.debug('The Are of the Triangle is'+R);
}

  void TrianglePeri (Decimal S)
{
    Decimal R;
    R=3*S;
    System.debug('The Perimete of the Equiletral Traingle is '+R);
    
}
    
}